### ISSUE TITLE
Docker Build Failing Due to Compile Time

### ISSUE THREAD

**Issue by ryanRfox** [bitshares/bitshares-core#1221]
**Bug Description**
The automated Docker builds are failing due to compile time constraints. It is possible to modify the `Dockerfile` to build only the `witness_node` and `cli_wallet` by default. This should allow the automated build to complete successfully. 

**Steps To Reproduce**
See Docker's automated build history

**Expected Behavior**
Docker's automated build process will complete successfully

## CORE TEAM TASK LIST
- [x] Evaluate / Prioritize Bug Report
- [X] Refine User Stories / Requirements
- [x] Define Test Cases
- [ ] Design / Develop Solution
- [ ] Perform QA/Testing
- [ ] Update Documentation

**Comment by abitmore** [comment]
Fixed by #1222.

**Comment by pmconrad** [comment]
Found list of docker resource limits - https://success.docker.com/article/what-are-the-current-resource-limits-placed-on-automated-builds
Note the 2GB RAM, that might be a problem.

The change did bring the build time down to 1:32, but still failed. Logs of latest build not available.
